#!/bin/bash

KEY=*.rsa
SRCDIR=$PWD
PKGDIR=$PWD/packages

command -v realpath &> /dev/null || realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

while [[ $# -gt 1 ]]; do
  case "$1" in
  -k|--key)
    KEY="$2"
    shift
    ;;
  -s|--src)
    SRCDIR="$2"
    shift
    ;;
  -p|--pkg)
    PKGDIR="$2"
    shift
    ;;
  *)
    ;;
  esac
  shift
done

KEYFILE=`basename $KEY`
PUBKEYFILE=$KEYFILE.pub
KEYDIR=`dirname $KEY`
KEYDIR=`realpath $KEYDIR`

echo "keyfile: $KEYFILE"
echo "keydir: $KEYDIR"
echo "srcdir: $SRCDIR"
echo "pkgdir: $PKGDIR"

docker run --rm -v $KEYDIR:/home/nbgallery/keys -v $PKGDIR:/home/nbgallery/packages -v $SRCDIR:/home/nbgallery/apks -e PACKAGER_PRIVKEY=/home/nbgallery/keys/$KEYFILE -e PACKAGER_PUBKEY=/home/nbgallery/keys/$PUBKEYFILE nbgallery/apkbuilder "$@"
